#!/usr/bin/env python

from sys import argv, exit
from os import path
from re import search
# don't forget to export DJANGO_SETTINGS_MODULE='settings' in bash
from django.shortcuts import get_object_or_404
from django.contrib.auth.models import User
from courses.models import Course
from documents.models import Document

if len(argv) < 3:
    print "Usage : add_doc <course> <file> [<file..>]"
    exit(1)

try:
    course = get_object_or_404(Course, slug=argv[1])
    adm = get_object_or_404(User, id=1)    # get the adminz
except Exception as e:
    print "Err, " + str(e)
    exit(1)

for filename in argv[2:]:
    print "File " + filename + "..",
    
    try:
        file = open(filename, 'rb')
    except Exception:
        print "fail"
        continue

    if not search(r'\.pdf$', filename):
        print "no pdf"
        continue

    d = Document.new(adm, course, file, 'R', False)
    course.add_document(d)
    print "ok"
