{% comment %}

# Copyright 2011, hast. All rights reserved.
#
# This program is free software: you can redistribute it and/or modify it 
# under the terms of the GNU Affero General Public License as published by 
# the Free Software Foundation, either version 3 of the License, or (at 
# your option) any later version.

{% endcomment %}
{% load markup %}
{% with first=object.msgs.all|first %}

{% include "thread_view.js" %}

<div>
  <div id="op_info">
    <strong>{{ first.owner.first_name }} {{ first.owner.last_name }}</strong><br>
    Other stats.<br><br>
    <input type="button" value="reply" onclick="reply({{ first.id }});"/>
    {% if user.get_profile.moderate %}<br>
    <input type="button" value="edit" onclick="edit({{ first.id }});"/><br>
    <input type="button" value="remove" onclick="remove({{ first.id }});"/>
    {% endif %}
  </div>

  <div id="outer_post">
    <small>Posted in
      <a href="{% url course_show object.referc.slug %}" 
         onclick="return Iload('{% url course_show object.referc.slug %}');">
        {{ object.referc.name }}
      </a>
      {% if object.referd %} :: 
        <a href="{% url view_file object.referd.id %}" 
           onclick="return Iload('{% url view_file object.referd.id %}');">
          {{ object.referd.name }}
        </a>
      {% endif %}
    </small>

    <h2>{{ object.subject|safe }}</h2>

    {% if object.referp %}
		<div id="left_post">
			<div id="inner_post">
				{{ first.text|markdown:'nl2br,smart_strong,headerid(level=3),' }}
			</div>
    	</div>
    	
    	<div id="right_post">
			About page<br>
			<a href="{% url view_file object.referd.id %}"
			   onclick="return Iload('{% url view_file object.referd.id %}');">
				<img id="page_image" src="{% url download_mpage object.referp.id %}"/>
			</a> 
		</div>
    {% else %}
		<div id="inner_post" class="real_inner_post">
			{{ first.text|markdown:'nl2br,smart_strong,headerid(level=3),' }}
		</div>
    {% endif %}
  </div>
</div>

<div style="clear: both; margin-top: 10px; padding-top: 10px;">
  <hr class="hr_view"/>
</div>

<div id="replies">
<!-- replies are dynamicly generated by JS -->
</div>

{% endwith %}
