INSERT INTO courses_course (slug, name) VALUES ('info-f-307', 'Génie logiciel et management des projets');
INSERT INTO courses_course (slug, name) VALUES ('info-f-403', 'Introduction to Language Theory and Compilation');
INSERT INTO courses_course (slug, name) VALUES ('info-f-405', 'Computer security');
INSERT INTO courses_course (slug, name) VALUES ('info-f-408', 'Computability and complexity');
INSERT INTO courses_course (slug, name) VALUES ('info-f-409', 'Learning dynamics');
INSERT INTO courses_course (slug, name) VALUES ('info-f-422', 'Statistical foundations of machine learning');
INSERT INTO courses_course (slug, name) VALUES ('info-f-514', 'Protocols, cryptanalysis and mathematical cryptology');
INSERT INTO courses_course (slug, name) VALUES ('info-h-300', 'Information and coding theory');
INSERT INTO courses_course (slug, name) VALUES ('info-h-410', 'Techniques of artificial intelligence');
INSERT INTO courses_course (slug, name) VALUES ('info-h-413', 'Heuristic optimisation');
INSERT INTO courses_course (slug, name) VALUES ('info-h-414', 'Swarm Intelligence');
INSERT INTO courses_course (slug, name) VALUES ('info-h-509', 'XML Technologies');
INSERT INTO courses_course (slug, name) VALUES ('math-h-404', 'Operational research');
INSERT INTO courses_course (slug, name) VALUES ('proj-h-402', 'Computing project');
